/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppCard: typeof import('./src/components/home/AppCard.vue')['default']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CountdownApp: typeof import('./src/components/countdown/CountdownApp.vue')['default']
    CountdownCard: typeof import('./src/components/countdown/CountdownCard.vue')['default']
    CountdownForm: typeof import('./src/components/countdown/CountdownForm.vue')['default']
    EditPanel: typeof import('./src/components/todo/EditPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/home/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./src/components/todo/TaskItem.vue')['default']
    TodoApp: typeof import('./src/components/todo/TodoApp.vue')['default']
  }
}
